spring:
  security:
    user:
      password: Test12345_
    filter:
      order: 20
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db_sales
    username: postgres
    password: 123@123a

service:
   jwt-secret:
   jwt-expiration: 60000 # 60 Seconds
